# all:
# 	g++ -c main2_v3.cpp
# 	g++ main2_v3.o -o sfml-app -lsfml-graphics -lsfml-window -lsfml-system
# 	./sfml-app
all:
	g++ -c welcomeScreen.cpp
	g++ welcomeScreen.o -o sfml-app -lsfml-graphics -lsfml-window -lsfml-system
	./sfml-app